### ISSUE TITLE
No output in "Show Plan"

### ISSUE THREAD

**Issue by brettcurtis** [hashicorp/learn-terraform-github-actions#15]
Thanks for the guide! I'm trying to get the GitHub Script stuff to work but getting no outputs:

![image](https://user-images.githubusercontent.com/1610100/95530979-57163f00-09ad-11eb-90d8-9b8101c2dbc4.png)

```yaml
    # Generates an execution plan for Terraform
    - name: Terraform Plan
      id: plan
      run: terraform plan -no-color
      continue-on-error: true

    - name: Update Pull Request
      uses: actions/github-script@0.9.0
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `
          #### Terraform Format and Style 🖌  : \`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙ : \`${{ steps.init.outcome }}\`
          #### Terraform Plan 📖 : \`${{ steps.plan.outcome }}\`

          <details><summary>Show Plan</summary>

          \`\`\`${process.env.PLAN}\`\`\`

          </details>


          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`*`;

          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
            })
```
